In [ ]:
import torch

In [ ]:
!nvidia-smi

Sun Aug 27 10:02:06 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   38C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## Tensors

In [ ]:
num = 1
type(num)

int

In [ ]:
t1 = torch.tensor(1.)
t1

tensor(1.)

In [ ]:
type(t1)

torch.Tensor

In [ ]:
t1.dtype

torch.float32

In [ ]:
## Vector

t2 = torch.tensor([1.,2,3,4])
t2

tensor([1., 2., 3., 4.])

In [ ]:
# Matrix 2d

t3 = torch.tensor([
    [5.,6],
    [6,8],
    [9,10]
])

t3

tensor([[ 5.,  6.],
        [ 6.,  8.],
        [ 9., 10.]])

In [ ]:
# 3dim
t4 = torch.tensor([
    [[11,12,13],
     [13,14,15]],
    [[15,16,17],
     [17,18,19.]]
])

t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

In [ ]:
print(t1)
t1.shape

tensor(1.)


torch.Size([])

In [ ]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [ ]:
print(t3)
t3.shape

tensor([[ 5.,  6.],
        [ 6.,  8.],
        [ 9., 10.]])


torch.Size([3, 2])

In [ ]:
print(t4)
t4.shape

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])


torch.Size([2, 2, 3])

In [ ]:
# Matrix 2d

t5 = torch.tensor([
    [5.,6,11],
    [6,8],
    [9,10,10]
])

t5

ValueError: ignored

## Tensor function

In [ ]:
t6 = torch.full((3,2),42)
t6

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [ ]:
t3

tensor([[ 5.,  6.],
        [ 6.,  8.],
        [ 9., 10.]])

In [ ]:
t6

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [ ]:
t7 = torch.cat((t3,t6))
t7

tensor([[ 5.,  6.],
        [ 6.,  8.],
        [ 9., 10.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])

In [ ]:
t8 = torch.sin(t7)
t8

tensor([[-0.9589, -0.2794],
        [-0.2794,  0.9894],
        [ 0.4121, -0.5440],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

In [ ]:
t9 = t8.reshape(3,2,2)
t9

tensor([[[-0.9589, -0.2794],
         [-0.2794,  0.9894]],

        [[ 0.4121, -0.5440],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])

In [ ]:
## Interroperability with numpy

import numpy as np

In [ ]:
x = np.array([[1,2],
             [3,4.]])
x

array([[1., 2.],
       [3., 4.]])

In [ ]:
type(x)

numpy.ndarray

In [ ]:
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [ ]:
type(y)

torch.Tensor

In [ ]:
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [ ]:
y.numpy()

array([[1., 2.],
       [3., 4.]])

## Neural Network using Pytorch

In [ ]:
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor, Lambda, Compose
import matplotlib.pyplot as plt

In [ ]:
training_data = datasets.FashionMNIST(
    root = "data",
    train = True,
    download = True,
    transform= ToTensor()
)

test_data = datasets.FashionMNIST(
    root = "data",
    train = False,
    download = True,
    transform= ToTensor()
)

100%|██████████| 26421880/26421880 [00:02<00:00, 12401112.05it/s]


Extracting data/FashionMNIST/raw/train-images-idx3-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 29515/29515 [00:00<00:00, 209697.08it/s]


Extracting data/FashionMNIST/raw/train-labels-idx1-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 4422102/4422102 [00:01<00:00, 3919616.32it/s]


Extracting data/FashionMNIST/raw/t10k-images-idx3-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 5148/5148 [00:00<00:00, 25735729.43it/s]

Extracting data/FashionMNIST/raw/t10k-labels-idx1-ubyte.gz to data/FashionMNIST/raw



In [ ]:
batch_size = 64

train_dataloader = DataLoader(training_data, batch_size= batch_size)
test_dataloader = DataLoader(test_data, batch_size= batch_size)

In [ ]:
train_dataloader

In [ ]:
for X, y in train_dataloader:
  print(X.shape)
  break

torch.Size([64, 1, 28, 28])


In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Define model
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10)
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

In [ ]:
model = NeuralNetwork().to(device)
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [ ]:
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=1e-3)

In [ ]:
def train(dataloader, model, loss_fn, optimizer):
    size = len(dataloader.dataset)
    model.train()
    for batch, (X, y) in enumerate(dataloader):
        X, y = X.to(device), y.to(device)

        # Compute prediction error
        pred = model(X)
        loss = loss_fn(pred, y)

        # Backpropagation
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if batch % 100 == 0:
            loss, current = loss.item(), batch * len(X)
            print(f"loss: {loss:>7f}  [{current:>5d}/{size:>5d}]")

In [ ]:
def test(dataloader, model, loss_fn):
    size = len(dataloader.dataset)
    num_batches = len(dataloader)
    model.eval()
    test_loss, correct = 0, 0
    with torch.no_grad():
        for X, y in dataloader:
            X, y = X.to(device), y.to(device)
            pred = model(X)
            test_loss += loss_fn(pred, y).item()
            correct += (pred.argmax(1) == y).type(torch.float).sum().item()
    test_loss /= num_batches
    correct /= size
    print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")

In [ ]:
epochs = 5
for t in range(epochs):
    print(f"Epoch {t+1}\n-------------------------------")
    train(train_dataloader, model, loss_fn, optimizer)
    test(test_dataloader, model, loss_fn)
print("Done!")

Epoch 1
-------------------------------
loss: 2.306978  [    0/60000]
loss: 2.292315  [ 6400/60000]
loss: 2.270795  [12800/60000]
loss: 2.263569  [19200/60000]
loss: 2.245961  [25600/60000]
loss: 2.223239  [32000/60000]
loss: 2.217420  [38400/60000]
loss: 2.191612  [44800/60000]
loss: 2.183591  [51200/60000]
loss: 2.144902  [57600/60000]
Test Error: 
 Accuracy: 53.0%, Avg loss: 2.146054 

Epoch 2
-------------------------------
loss: 2.159363  [    0/60000]
loss: 2.144012  [ 6400/60000]
loss: 2.084967  [12800/60000]
loss: 2.095652  [19200/60000]
loss: 2.046930  [25600/60000]
loss: 1.994735  [32000/60000]
loss: 2.004030  [38400/60000]
loss: 1.936210  [44800/60000]
loss: 1.934894  [51200/60000]
loss: 1.847322  [57600/60000]
Test Error: 
 Accuracy: 59.9%, Avg loss: 1.856882 

Epoch 3
-------------------------------
loss: 1.898442  [    0/60000]
loss: 1.859084  [ 6400/60000]
loss: 1.743849  [12800/60000]
loss: 1.773870  [19200/60000]
loss: 1.679706  [25600/60000]
loss: 1.639033  [32000/600

In [ ]:
#save model
torch.save(model.state_dict(), "model.pth")
print("Saved PyTorch Model State to model.pth")

Saved PyTorch Model State to model.pth


In [ ]:
model = NeuralNetwork()
model.load_state_dict(torch.load("model.pth"))

<All keys matched successfully>

In [ ]:
## Prediction

classes = [
    "T-shirt/top",
    "Trouser",
    "Pullover",
    "Dress",
    "Coat",
    "Sandal",
    "Shirt",
    "Sneaker",
    "Bag",
    "Ankle boot",
]


model.eval()


NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)

In [ ]:
classes[9]

'Ankle boot'

In [ ]:
x, y = test_data[0][0], test_data[0][1]

In [ ]:
x

tensor([[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,

In [ ]:
y

9

In [ ]:
with torch.no_grad():
    pred = model(x)
    predicted, actual = classes[pred[0].argmax(0)], classes[y]
    print(f'Predicted: "{predicted}", Actual: "{actual}"')

Predicted: "Ankle boot", Actual: "Ankle boot"
