In [ ]:
import torch

In [ ]:
!nvidia-smi

Sun Aug 27 10:06:41 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P8    11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
num = 1
type(num)

int

In [ ]:
t1 = torch.tensor(1.)
t1

tensor(1.)

In [ ]:
type(t1)

torch.Tensor

In [ ]:
t1.dtype

torch.float32

In [ ]:
#Vector
t2 = torch.tensor([1., 2, 3, 4]) # all values considered as float
t2

tensor([1., 2., 3., 4.])

In [ ]:
#Matrix

t3 = torch.tensor([
    [5,6],
    [6,8],
    [9,10]
])

In [ ]:
t3 #  2D Matrix..

tensor([[ 5,  6],
        [ 6,  8],
        [ 9, 10]])

In [ ]:
#3D matrix...

t4 = torch.tensor([
    [11,12,13],
    [14,15,16],
    [17,18,19.]
])
t4

tensor([[11., 12., 13.],
        [14., 15., 16.],
        [17., 18., 19.]])

In [ ]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [ ]:
t5 = torch.tensor([
    [5,6,11],
    [6,8],
    [9,10,10]
]) # all dimensions should be same

ValueError: ignored

Tensor Function

In [ ]:
t6 = torch.full((3,2), 42)
t6

tensor([[42, 42],
        [42, 42],
        [42, 42]])

Neural Network with pytorch

In [ ]:
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor, Lambda, Compose
import matplotlib.pyplot as plt

In [ ]:
training_data = datasets.FashionMNIST(
    root = "data",
    train = True,
    download = True,
    transform= ToTensor()
)

test_data = datasets.FashionMNIST(
    root = "data",
    train = False,
    download = True,
    transform= ToTensor()
)