In [34]:
from keras import Sequential

In [43]:
from keras.layers import Dense, SimpleRNN

In [50]:
model1 = Sequential()

In [51]:
model1.add(SimpleRNN(3, input_shape=(4,5)))

#3 - no of hidden layer
#4 - max length of sentence
#5 - no of words in vocabulary

model1.add(Dense(1, activation="sigmoid")) # output layer

In [ ]:
model.summary()

In [ ]:
model.get_weights()[0]

In [1]:
from keras.datasets import imdb

In [2]:
imdb.load_data()

17464789/17464789 [==============================] - 0s 0us/step


((array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 22665, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 21631, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 31050, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
         list([1, 19

In [10]:
(X_train,y_train),(X_test, y_test) = imdb.load_data()

In [9]:
import numpy as np

In [12]:
X_train.shape

(25000,)

In [14]:
X_train[0]

[1,
 14,
 22,
 16,
 43,
 530,
 973,
 1622,
 1385,
 65,
 458,
 4468,
 66,
 3941,
 4,
 173,
 36,
 256,
 5,
 25,
 100,
 43,
 838,
 112,
 50,
 670,
 22665,
 9,
 35,
 480,
 284,
 5,
 150,
 4,
 172,
 112,
 167,
 21631,
 336,
 385,
 39,
 4,
 172,
 4536,
 1111,
 17,
 546,
 38,
 13,
 447,
 4,
 192,
 50,
 16,
 6,
 147,
 2025,
 19,
 14,
 22,
 4,
 1920,
 4613,
 469,
 4,
 22,
 71,
 87,
 12,
 16,
 43,
 530,
 38,
 76,
 15,
 13,
 1247,
 4,
 22,
 17,
 515,
 17,
 12,
 16,
 626,
 18,
 19193,
 5,
 62,
 386,
 12,
 8,
 316,
 8,
 106,
 5,
 4,
 2223,
 5244,
 16,
 480,
 66,
 3785,
 33,
 4,
 130,
 12,
 16,
 38,
 619,
 5,
 25,
 124,
 51,
 36,
 135,
 48,
 25,
 1415,
 33,
 6,
 22,
 12,
 215,
 28,
 77,
 52,
 5,
 14,
 407,
 16,
 82,
 10311,
 8,
 4,
 107,
 117,
 5952,
 15,
 256,
 4,
 31050,
 7,
 3766,
 5,
 723,
 36,
 71,
 43,
 530,
 476,
 26,
 400,
 317,
 46,
 7,
 4,
 12118,
 1029,
 13,
 104,
 88,
 4,
 381,
 15,
 297,
 98,
 32,
 2071,
 56,
 26,
 141,
 6,
 194,
 7486,
 18,
 4,
 226,
 22,
 21,
 134,
 476,
 26,
 480,
 5

In [15]:
import numpy as np
sent=[
    "India won Worldcup",
    "Rohit played very well",
    "above all is my imagination",
    "bharat mata ki jay",
    "definatly we gonna win next worldcup"
]

In [16]:
sent

['India won Worldcup',
 'Rohit played very well',
 'above all is my imagination',
 'bharat mata ki jay',
 'definatly we gonna win next worldcup']

In [17]:
from keras.preprocessing.text import Tokenizer # integer encoding

In [18]:
tokenizer = Tokenizer()

In [19]:
tokenizer.fit_on_texts(sent)

In [21]:
tokenizer.word_index # vocabulary index...

{'worldcup': 1,
 'india': 2,
 'won': 3,
 'rohit': 4,
 'played': 5,
 'very': 6,
 'well': 7,
 'above': 8,
 'all': 9,
 'is': 10,
 'my': 11,
 'imagination': 12,
 'bharat': 13,
 'mata': 14,
 'ki': 15,
 'jay': 16,
 'definatly': 17,
 'we': 18,
 'gonna': 19,
 'win': 20,
 'next': 21}

In [22]:
tokenizer.word_counts # vocabulary..

OrderedDict([('india', 1),
             ('won', 1),
             ('worldcup', 2),
             ('rohit', 1),
             ('played', 1),
             ('very', 1),
             ('well', 1),
             ('above', 1),
             ('all', 1),
             ('is', 1),
             ('my', 1),
             ('imagination', 1),
             ('bharat', 1),
             ('mata', 1),
             ('ki', 1),
             ('jay', 1),
             ('definatly', 1),
             ('we', 1),
             ('gonna', 1),
             ('win', 1),
             ('next', 1)])

In [23]:
tokenizer.document_count # number of sentences...

5

In [26]:
tokenizer.texts_to_sequences(sent) #sequence for sentences.. integer encoding..

[[2, 3, 1],
 [4, 5, 6, 7],
 [8, 9, 10, 11, 12],
 [13, 14, 15, 16],
 [17, 18, 19, 20, 21, 1]]

In [27]:
encoding = tokenizer.texts_to_sequences(sent)

In [30]:
from keras.utils import pad_sequences # to add padding in your sentence

In [31]:
pad_sequences(encoding, padding="post")

array([[ 2,  3,  1,  0,  0,  0],
       [ 4,  5,  6,  7,  0,  0],
       [ 8,  9, 10, 11, 12,  0],
       [13, 14, 15, 16,  0,  0],
       [17, 18, 19, 20, 21,  1]], dtype=int32)

In [32]:
# movies dataset has same integer encoding

y_train

array([1, 0, 0, ..., 0, 1, 0])

In [35]:
model = Sequential()

In [36]:
len(X_train[0]) # length of 1st movie reviews

218

In [38]:
len(X_train[1]) # length of 2nd movie reviews

189

In [39]:
len(X_train[2]) # length of 2nd movie reviews

141

In [40]:
mylist = []
for review in X_train:
  mylist.append(len(review))

min(mylist)

11

In [41]:
X_train = pad_sequences(X_train, padding="post", maxlen=50)
X_test = pad_sequences(X_train, padding="post", maxlen=50)

In [44]:
model.add(SimpleRNN(32,input_shape=(50,1)))

In [45]:
model.add(Dense(1,activation="sigmoid"))

In [46]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn (SimpleRNN)      (None, 32)                1088      
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 1121 (4.38 KB)
Trainable params: 1121 (4.38 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [48]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [49]:
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=5)

Epoch 1/5
782/782 [==============================] - 34s 36ms/step - loss: 0.7129 - accuracy: 0.5040 - val_loss: 0.6950 - val_accuracy: 0.5017
Epoch 2/5
782/782 [==============================] - 29s 37ms/step - loss: 0.6931 - accuracy: 0.5059 - val_loss: 0.6948 - val_accuracy: 0.4985
Epoch 3/5
782/782 [==============================] - 28s 36ms/step - loss: 0.6929 - accuracy: 0.5060 - val_loss: 0.6970 - val_accuracy: 0.4986
Epoch 4/5
782/782 [==============================] - 28s 36ms/step - loss: 0.6932 - accuracy: 0.5050 - val_loss: 0.6946 - val_accuracy: 0.4996
Epoch 5/5
782/782 [==============================] - 29s 38ms/step - loss: 0.6931 - accuracy: 0.5038 - val_loss: 0.6962 - val_accuracy: 0.4987


In [52]:
model.predict(X_test)

782/782 [==============================] - 4s 6ms/step


array([[0.4261903 ],
       [0.48301643],
       [0.48323557],
       ...,
       [0.48340768],
       [0.38940182],
       [0.49966377]], dtype=float32)

In [53]:
model.evaluate(X_test, y_test)

782/782 [==============================] - 6s 7ms/step - loss: 0.6962 - accuracy: 0.4987


[0.6961787343025208, 0.4986799955368042]

In [54]:
loss, accuracy = model.evaluate(X_test, y_test)

782/782 [==============================] - 5s 7ms/step - loss: 0.6962 - accuracy: 0.4987
