#### ordinal encoding is used to encode the ordinal categorical data like reviews, grade, ratings 
#### label encoding is used only on target(for output features) categorical data

In [31]:
import numpy as np
import pandas as pd

In [32]:
df = pd.read_csv('customer.csv')

In [33]:
df.sample(5)

age  gender   review education purchased
25   57  Female     Good    School        No
19   97    Male     Poor        PG       Yes
36   34  Female     Good        UG       Yes
4    16  Female  Average        UG        No
8    65  Female  Average        UG        No

In [34]:
df = df.iloc[:,2:]

In [35]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop('purchased', axis=1),
                                                    df['purchased'],
                                                    test_size=0.3,
                                                    random_state=0)

X_train.shape, X_test.shape

((35, 2), (15, 2))

In [36]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [37]:
from sklearn.preprocessing import OrdinalEncoder

In [38]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']]) # list of categories in lower to higher values

In [39]:
oe.fit(X_train) # learning from train

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [40]:
X_train = oe.transform(X_train) #implementing on both...
X_test = oe.transform(X_test)

In [41]:
X_train

array([[0., 0.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [2., 2.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [1., 0.],
       [2., 0.],
       [1., 0.],
       [0., 1.],
       [2., 0.],
       [2., 1.],
       [0., 1.],
       [0., 0.],
       [1., 2.],
       [1., 2.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [1., 2.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [2., 2.],
       [1., 1.]])

In [42]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [43]:
X_train

array([[0., 0.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [2., 2.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [1., 0.],
       [2., 0.],
       [1., 0.],
       [0., 1.],
       [2., 0.],
       [2., 1.],
       [0., 1.],
       [0., 0.],
       [1., 2.],
       [1., 2.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [1., 2.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [2., 2.],
       [1., 1.]])

In [44]:
from sklearn.preprocessing import LabelEncoder

In [45]:
le = LabelEncoder()

In [46]:
le.fit(y_train)

LabelEncoder()

In [47]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [48]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [49]:
X_test

array([[0., 0.],
       [2., 1.],
       [2., 1.],
       [2., 2.],
       [2., 2.],
       [0., 2.],
       [2., 0.],
       [0., 0.],
       [0., 2.],
       [1., 1.],
       [2., 2.],
       [0., 0.],
       [0., 2.],
       [1., 0.],
       [2., 0.]])

In [50]:
y_train

array([1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0])

In [52]:
from sklearn.metrics import accuracy_score, confusion_matrix # r2square, rscore

from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()#creating model
model.fit(X_train, y_train) # training model with default parameter..

y_predict = model.predict(X_test) # predicting for test data

accuracy_score(y_test,y_predict)


0.7333333333333333

In [54]:
confusion_matrix(y_test,y_predict)

array([[7, 1],
       [3, 4]], dtype=int64)