In [17]:
import pandas as pd
data = pd.read_csv("https://raw.githubusercontent.com/shrikant-temburwar/Wine-Quality-Dataset/master/winequality-red.csv", sep=";")

In [18]:
data

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [28]:
import seaborn as sns
sns.displot(data['citric acid'], kde=True) # checking data is normally distributed or not...

In [20]:
from scipy import  stats
stats.shapiro(data['volatile acidity'])

# p value is less than 0.05 i.e 5% we reject null hypothesis..

ShapiroResult(statistic=0.9743338823318481, pvalue=2.686385373947307e-16)

In [21]:
stats.shapiro(data['citric acid'])

ShapiroResult(statistic=0.955294668674469, pvalue=1.0233944777578548e-21)

In [24]:
from numpy.random import randn
mydata = randn(100) # 100 datapoints which follow normal distribution

In [25]:
sns.displot(mydata)

In [26]:
stats.shapiro(mydata)

ShapiroResult(statistic=0.9974769353866577, pvalue=0.9997492432594299)

In [27]:
result = stats.shapiro(mydata)

In [ ]:
#null hypothesis -> data is normal distribution
if p<= result[1]:
    print("reject the null hyphothesis")
else:
    print("accept the null hypothesis")

In [30]:
from scipy import stats
stats.normaltest(data['citric acid'])

#pvalue is <0.05 reject null hypothesis

NormaltestResult(statistic=152.039214793795, pvalue=9.662822259281018e-34)

In [31]:
from scipy import stats
stats.normaltest(mydata)

#pvalue is >0.05 accept null hypothesis that means data is normally distributed...

NormaltestResult(statistic=0.0415762718729775, pvalue=0.9794264478567106)

In [40]:
from statsmodels.stats.weightstats import ztest
sample_mean_id=110
mean_std_dev=15
mean_population =100
# alpha= 0.05
# ci=95%

In [42]:
data = mean_std_dev * randn(50)+mean_population

In [44]:
import numpy as np
np.mean(data)

98.96043701808053

In [45]:
np.std(data)

17.95298431141977

In [46]:
null_value = 50

In [47]:
from statsmodels.stats.weightstats import ztest
ztest(data, value=null_value, alternative='larger')

(19.090032786836442, 1.527887864409183e-81)

In [48]:
ztest(data, value=100, alternative='larger')

(-0.40533321631699437, 0.6573837031688067)

In [52]:
#Test types...
#one sample ttest (one independent sample)
#two sample t-test (two independent sample test)
#apired sample t-test ( two sample the same population on different time interval)

import random
population = np.random.randint(10,50,50)

In [58]:
#selecting random sample
sample1 = np.random.choice(population, 20)

In [59]:
sample2 = np.random.choice(population,20)

In [60]:
sample2.mean()

30.9

In [61]:
sample1.mean()

28.15

In [63]:
my_cricket_score = [22,38,19,15,48,11,10,49,34]
virat_scricket_score = [34,32,45,34,12,23,34,45,67] 

np.mean(my_cricket_score)
np.mean(virat_scricket_score)


36.22222222222222

In [64]:
np.mean(my_cricket_score)

27.333333333333332

In [66]:
import scipy
scipy.stats.ttest_1samp(my_cricket_score, 10)

Ttest_1sampResult(statistic=3.39934634239519, pvalue=0.009369519982811478)

In [ ]:
# we are going to reject the null hypothesis
p_value<=0.05

#accept
p_value>0.05

In [68]:
scipy.stats.ttest_1samp(my_cricket_score, 16)

Ttest_1sampResult(statistic=2.2226495315660855, pvalue=0.05694625587889119)

In [70]:
first_sample_mean = np.mean(my_cricket_score)
second_sample_mean = np.mean(virat_scricket_score)

# my_null_hypothesis is both sample will be same

In [71]:
scipy.stats.ttest_ind(my_cricket_score,virat_scricket_score)

Ttest_indResult(statistic=-1.2288076127325036, pvalue=0.2369114235926428)

In [74]:
np.mean(my_cricket_score)

27.333333333333332

In [75]:
np.mean(virat_scricket_score)

36.22222222222222

In [76]:
# both mean have big difference so we reject it as pvalue is < 0.05...

In [78]:
#paired t-test
#here sample will be from same dataset....
first_inning = [22,38,19,15,48,11,10,49,34]
second_inning = [34,32,45,34,12,23,34,45,67] 

In [81]:
print(np.mean(first_inning))
print(np.mean(second_inning))

27.333333333333332
36.22222222222222


In [82]:
scipy.stats.ttest_rel(first_inning, second_inning)

Ttest_relResult(statistic=-1.2524102123471454, pvalue=0.24579185520727836)

In [ ]:
#here we hv different mean and pvalue is <0.05 also so we r rejecting

In [89]:
first_inning = [22,38,39,45,48,21,20,49,34]
second_inning = [34,36,45,49,12,23,34,45,37] 

In [90]:
print(np.mean(first_inning))
print(np.mean(second_inning))

35.111111111111114
35.0


In [91]:
scipy.stats.ttest_rel(first_inning, second_inning)

Ttest_relResult(statistic=0.022727272727272728, pvalue=0.98242447393317)

In [92]:
#here we hv different mean and pvalue is >0.05 also so we r rejecting

In [93]:
#chi-square test...
import seaborn as sns
dataset = sns.load_dataset('tips')

In [94]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


In [95]:
dataset.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [96]:
dataset.sex

0      Female
1        Male
2        Male
3        Male
4      Female
        ...  
239      Male
240    Female
241      Male
242      Male
243    Female
Name: sex, Length: 244, dtype: category
Categories (2, object): ['Male', 'Female']

In [98]:
dataset.smoker

0       No
1       No
2       No
3       No
4       No
      ... 
239     No
240    Yes
241    Yes
242     No
243     No
Name: smoker, Length: 244, dtype: category
Categories (2, object): ['Yes', 'No']

In [99]:
pd.crosstab(dataset['sex'],dataset['smoker'])

smoker  Yes  No
sex            
Male     60  97
Female   33  54

In [100]:
dataset_tbl = pd.crosstab(dataset['sex'],dataset['smoker'])

In [104]:
arr = dataset_tbl.values
arr
#this is observed value - real value of data

array([[60, 97],
       [33, 54]], dtype=int64)

In [106]:
import scipy.stats as stats
stats_test, p, dof,expected_value = stats.chi2_contingency(arr)

In [107]:
p

1.0

In [108]:
expected_value

array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]])

In [109]:
dof

1

In [110]:
stats_test

0.0

In [113]:
no_of_rows = dataset_tbl.iloc[0:2,0]
no_of_rows

sex
Male      60
Female    33
Name: Yes, dtype: int64

In [114]:
no_of_column = dataset_tbl.iloc[0,0:2]
no_of_column

smoker
Yes    60
No     97
Name: Male, dtype: int64

In [115]:
dof = (len(no_of_rows)-1) * (len(no_of_column)-1)

In [116]:
dof

1

In [119]:
from scipy.stats import chi2
chi = sum([(o-e)**2./e for o,e in zip(arr, expected_value)])

In [120]:
chi

array([0.00119737, 0.00073745])

In [125]:
chi_stats = chi[0]+chi[1]

In [126]:
alpha = 0.05

In [127]:
from scipy.stats import chi2
critical_value = chi2.ppf(1-alpha, df=dof)
critical_value


3.841458820694124

In [129]:
if chi_stats>= critical_value:
    print("reject h0, there is a relation ship between 2 categoriccal data..")
else:
    print("retain h0, thre is no relationship between 2 categorical data..")

retain h0, thre is no relationship between 2 categorical data..


In [132]:
p_value = 1-chi2.cdf(x=chi_stats, df=dof)

In [133]:
# p_value

if p_value <= alpha:
    print("reject h0, there is a relationship between 2 categorical data...")
else:
    print("retain h0, there is no relationship between 2 categorical data")

retain h0, there is no relationship between 2 categorical data


In [ ]:
##ANOVA-TEST