In [1]:
import numpy as np

In [2]:
range(10) #generator for number

range(0, 10)

In [3]:
list(range(10))#generate number in list form 

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
list(range(3,10)) #only int numbers can be generated

[3, 4, 5, 6, 7, 8, 9]

In [7]:
list(range(3,10.5))

TypeError: 'float' object cannot be interpreted as an integer

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0.5,10) # can generate float number...

array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

In [8]:
np.arange(5,-4,-1)# jump size is -1

array([ 5,  4,  3,  2,  1,  0, -1, -2, -3])

In [10]:
dv= np.arange(5,-4,.5)# jump size is -0.5
dv

array([], dtype=float64)

In [11]:
np.linspace(1,5,20)# 1 to 5 range is divided in 20 segments...

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [12]:
list(np.linspace(1,5,20))# 1 to 5 range is divided in 20 segments... convert in list

[1.0,
 1.2105263157894737,
 1.4210526315789473,
 1.631578947368421,
 1.8421052631578947,
 2.052631578947368,
 2.263157894736842,
 2.473684210526316,
 2.6842105263157894,
 2.894736842105263,
 3.1052631578947367,
 3.3157894736842106,
 3.526315789473684,
 3.7368421052631575,
 3.9473684210526314,
 4.157894736842105,
 4.368421052631579,
 4.578947368421052,
 4.789473684210526,
 5.0]

In [14]:
list(np.linspace(1,5,20,retstep=True))## step size return

[array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
        2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
        3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
        4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ]),
 0.21052631578947367]

In [15]:
np.logspace(1,50,10)# base=10 by default...

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((3,5))# 3 rows 5 column

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.zeros((3,5,2))# 3 index 5 rowa and 2 column

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [22]:
np.ones((3,4,2))# 3 index 4 rowa and 2 column

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [23]:
np.ones((3,4,2)) * 5 # 3 index 4 rowa and 2 column * into 5

array([[[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]]])

In [27]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
np.eye(4) # square matrix diagonal elements are same.. 
# identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
a = np.eye(4)
a.shape # dimensions of array

(4, 4)

In [32]:
a.size #number of elements

16

In [33]:
a.ndim # 2D data

2

In [34]:
a1 = np.random.randn(3,4)
a1

array([[-1.55641566,  0.27216164,  0.59725738,  0.04622429],
       [-0.23485533, -1.32350194,  0.50563092, -0.10063952],
       [-1.38245408, -1.1499553 , -1.67310408,  0.14666138]])

In [35]:
import pandas as pd

In [36]:
pd.DataFrame(a1)

0         1         2         3
0 -1.556416  0.272162  0.597257  0.046224
1 -0.234855 -1.323502  0.505631 -0.100640
2 -1.382454 -1.149955 -1.673104  0.146661

In [37]:
a1

array([[-1.55641566,  0.27216164,  0.59725738,  0.04622429],
       [-0.23485533, -1.32350194,  0.50563092, -0.10063952],
       [-1.38245408, -1.1499553 , -1.67310408,  0.14666138]])

In [38]:
#to access particluar element
a1[1][1]


-1.323501936706716

In [40]:
# to access elementsss
a1[0:2, 0:2] # rows, upper bound of columns

array([[-1.55641566,  0.27216164],
       [-0.23485533, -1.32350194]])

In [41]:
a1[[0,1],0:2]

array([[-1.55641566,  0.27216164],
       [-0.23485533, -1.32350194]])

In [42]:
a1[[1,2],3]#[1,2] that is rows number ,3 is column

array([-0.10063952,  0.14666138])

In [46]:
m1 = np.random.randint(1,3,(3,3))#3x3 matrix
m1

array([[1, 1, 2],
       [2, 2, 1],
       [2, 2, 2]])

In [47]:
m2 = np.random.randint(1,3,(3,3))#3x3 matrix
m2

array([[1, 1, 2],
       [1, 1, 2],
       [2, 1, 2]])

In [48]:
m1*m2 # its elementwise multiplication.. its not matrix multiplication

array([[1, 1, 4],
       [2, 2, 2],
       [4, 2, 4]])

In [49]:
m1@m2 # matrix multipliaction
#column of m1 must be = row of m2 is true..to do mulplication

array([[ 6,  4,  8],
       [ 6,  5, 10],
       [ 8,  6, 12]])

In [50]:
pow(m1,4) #power of each elemtns eg m1**2

array([[ 1,  1, 16],
       [16, 16,  1],
       [16, 16, 16]], dtype=int32)

In [51]:
np.sqrt(m1) # square root of all elemtns

array([[1.        , 1.        , 1.41421356],
       [1.41421356, 1.41421356, 1.        ],
       [1.41421356, 1.41421356, 1.41421356]])

In [52]:
np.log(m1)# logrithm

array([[0.        , 0.        , 0.69314718],
       [0.69314718, 0.69314718, 0.        ],
       [0.69314718, 0.69314718, 0.69314718]])

In [53]:
np.log10(m1)#log base 10 of each

array([[0.     , 0.     , 0.30103],
       [0.30103, 0.30103, 0.     ],
       [0.30103, 0.30103, 0.30103]])

In [54]:
np.exp(m1) # exponent of element

array([[2.71828183, 2.71828183, 7.3890561 ],
       [7.3890561 , 7.3890561 , 2.71828183],
       [7.3890561 , 7.3890561 , 7.3890561 ]])

In [55]:
m1**2

array([[1, 1, 4],
       [4, 4, 1],
       [4, 4, 4]], dtype=int32)